// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf63sCfrJ83-SDSD7QTX3qetDVwLK0lG8',
    appId: '1:131559038805:web:4681a983b82699d2ed99dc',
    messagingSenderId: '131559038805',
    projectId: 'projectadmin-557bf',
    authDomain: 'projectadmin-557bf.firebaseapp.com',
    storageBucket: 'projectadmin-557bf.appspot.com',
    measurementId: 'G-ZFHEC59N7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAO6hWtivdP1OGjmWmQp0zVIQV1o2efCc',
    appId: '1:131559038805:android:4685816d488d05a8ed99dc',
    messagingSenderId: '131559038805',
    projectId: 'projectadmin-557bf',
    storageBucket: 'projectadmin-557bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFK8O4bAfFObgwfxbMVp5jDtnCJZzA02U',
    appId: '1:131559038805:ios:81f21df235708449ed99dc',
    messagingSenderId: '131559038805',
    projectId: 'projectadmin-557bf',
    storageBucket: 'projectadmin-557bf.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFK8O4bAfFObgwfxbMVp5jDtnCJZzA02U',
    appId: '1:131559038805:ios:f8756752d6d760e1ed99dc',
    messagingSenderId: '131559038805',
    projectId: 'projectadmin-557bf',
    storageBucket: 'projectadmin-557bf.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
